### ISSUE TITLE
V2.6 Version is not compatible

### ISSUE THREAD

**Issue by grusirna** [eamigo86/graphene-django-extras#121]
Graphene-django updated to 2.6, adding "DjangoListField only accepts DjangoObjectType types" causes version incompatibility。

**Comment by obisimon** [comment]
@grusirna, i use the `DjangoObjectType` directly from graphene_django as a workaround

`from graphene_django import DjangoObjectType`
instead of
`from graphene_django_extras import DjangoObjectType`

but I have not really tested it

**Comment by eamigo86** [comment]
Hi @grusirna, this was fixed in the last release. Thanks for report

**Comment by sarendsen** [comment]
still receiving this error with graphene-django==2.6.0 and graphene-django-extras==0.4.7

**Comment by eamigo86** [comment]
Hi @grusirna, thanks for report it, I will check that
